version: '3.5'

services:
  db:
    image: postgres:15
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Configurações para o Postgres não "engasgar" com pouco recurso
    command: [
      "postgres", 
      "-c", "max_connections=200", 
      "-c", "shared_buffers=256MB", 
      "-c", "effective_cache_size=768MB"
    ]
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1.2GB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5

  api1: &api
    build: .
    image: rinha-api
    hostname: api1
    environment:
      - DATABASE_URL=postgresql://admin:123@db:5432/rinha
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'

  api2:
    <<: *api
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.4GB'

